const frases = {
  triste: [
   "Incluso en la noche más oscura, el sol volverá a brillar.",
    "Permítete sentir, pero no pierdas la esperanza.",
    "Tus lágrimas riegan el terreno para tu crecimiento.",
    "Ser fuerte no es no llorar, es seguir adelante.",
    "Lo estás haciendo lo mejor que puedes, y eso es suficiente.",
    "El dolor también es parte del camino hacia la sanación.",
    "Hoy puede doler, pero mañana tendrás más fuerza.",
    "Las tormentas también hacen crecer flores.",
    "Está bien no estar bien.",
    "Después de la lluvia, siempre vuelve el sol.",
    "La tristeza es un puente hacia algo nuevo.",
    "Cada lágrima es un paso hacia la paz.",
    "Tu corazón valiente sigue latiendo.",
    "No te rindas, cada día trae su aprendizaje.",
    "La oscuridad no dura para siempre.",
    "Respira hondo, el aire trae esperanza.",
    "Un pequeño paso hoy es un gran avance mañana.",
    "Acepta lo que sientes sin juzgarte.",
    "El dolor abre puertas a nuevas fuerzas.",
    "Estas vivo, y eso ya es un triunfo.",
    "Un nuevo amanecer te espera.",
    "Tus cicatrices cuentan tu historia de superación.",
    "No estás solo, compartes fuerza con otros.",
    "Permite que la calma te alcance.",
    "La tristeza también enseña y transforma.",
    "Estás creciendo, aunque no lo veas.",
    "El silencio también puede ser sanador.",
    "Confía en que todo tiene un propósito.",
    "El sol volverá a iluminar tu camino.",
    "Tu corazón se curará con paciencia."
  ],
  estresado: [
    "Respira. Estás haciendo lo mejor que puedes.",
    "Una mente tranquila ve soluciones, no problemas.",
    "Hoy puede ser difícil, pero no será así siempre.",
    "Tu paz mental es una prioridad, cuídala.",
    "No tienes que controlarlo todo.",
    "Haz una pausa, lo estás haciendo bien.",
    "La presión es parte del crecimiento, pero no lo es todo.",
    "Escucha a tu cuerpo, a veces solo necesita un respiro.",
    "No eres tu productividad.",
    "Un día a la vez, y todo estará bien.",
    "Permítete un momento de descanso.",
    "No cargues más de lo que puedes sostener.",
    "Respira hondo y suelta la tensión.",
    "Ordena tus prioridades con claridad.",
    "Un pequeño descanso puede cambiar el día.",
    "No necesitas resolverlo todo ahora.",
    "El equilibrio es más valioso que el esfuerzo constante.",
    "Está bien tomarte un respiro.",
    "Haz una cosa a la vez.",
    "Pequeños pasos también avanzan.",
    "Con calma verás mejor el camino.",
    "Aprende a decir ‘ya basta’ cuando lo necesites.",
    "Tu cuerpo y mente te lo agradecerán.",
    "El estrés te avisa: necesitas cuidar de ti.",
    "No tienes que estar en 10 lugares a la vez.",
    "Menos es más: simplifica tu día.",
    "Tiempo de calidad contigo también cuenta.",
    "Desconecta un rato, recarga energía.",
    "Pequeñas pausas suman grandes cambios.",
    "Eres humano: mereces descanso."
  ],
  feliz: [
    "Disfruta este momento. Te lo mereces.",
    "Tu alegría ilumina a quienes te rodean.",
    "Sigue sonriendo, estás brillando con fuerza.",
    "La felicidad que das, vuelve multiplicada.",
    "Agradece cada instante de luz.",
    "Tu sonrisa es poderosa.",
    "Lo que te hace feliz, hazlo más seguido.",
    "Celebra tus logros, grandes o pequeños.",
    "Comparte tu felicidad, es contagiosa.",
    "Hoy es un buen día para ser feliz.",
    "La vida sonríe contigo.",
    "Tu buena vibra es un regalo.",
    "Esa felicidad que sientes está creciendo.",
    "Eres luz en los días grises de otros.",
    "Disfruta de cada pequeño detalle.",
    "La alegría te hace fuerte.",
    "El presente contiene tu felicidad.",
    "Que tu sonrisa contagie tu entorno.",
    "Valora lo que tienes y celebra lo que eres.",
    "Tu bienestar es tu triunfo.",
    "Ríe sin motivo, solo por sentirte vivo.",
    "La felicidad sana el alma.",
    "Haz lo que nutra tu corazón.",
    "Hoy es un buen día para crear recuerdos.",
    "El buen ánimo también es un logro.",
    "Contagia tu energía positiva.",
    "Disfruta los sonidos de tu felicidad.",
    "Haz de la gratitud tu hábito diario.",
    "Eres dueño de tu felicidad."
  ],
  cansado: [
    "Descansar también es parte del proceso.",
  "Incluso los más fuertes necesitan una pausa.",
  "No te castigues por descansar, te lo has ganado.",
  "Recargar energía es avanzar con más fuerza.",
  "Escucha a tu cuerpo: descansar también es crecer.",
  "Tu valor no se mide por lo que haces sin parar.",
  "Detente, respira, y vuelve con más claridad.",
  "Está bien soltar lo que pesa.",
  "A veces avanzar es simplemente no rendirse.",
  "Dormir es parte del éxito también.",
  "Tu cuerpo merece respeto, no castigo.",
  "La pausa es parte del ritmo del progreso.",
  "Rendirse por hoy no es rendirse para siempre.",
  "La fatiga es señal de esfuerzo, no de debilidad.",
  "Hoy descansas, mañana brillas.",
  "Escucha tu agotamiento como una necesidad, no como una excusa.",
  "El descanso es el combustible de la perseverancia.",
  "Dormir bien también es productividad.",
  "El autocuidado no es egoísmo, es necesidad.",
  "A veces lo más productivo es no hacer nada.",
  "Tu mente también necesita silencio.",
  "No estás fracasando, solo estás cansado.",
  "Tú no eres pereza, eres humano.",
  "Un respiro no detiene tu camino, lo fortalece.",
  "Las pausas te acercan a tu mejor versión.",
  "Ser fuerte también es saber cuándo parar.",
  "Date permiso para descansar sin culpa.",
  "La energía que guardas hoy, te impulsa mañana.",
  "Escoge la recuperación en lugar del agotamiento.",
  "Dormir no es perder tiempo, es recuperarlo."
  ],
  motivado: [
   "Sigue adelante, estás más cerca de lo que crees.",
  "El esfuerzo de hoy será tu éxito mañana.",
  "Cuando crees en ti, todo es posible.",
  "Tú puedes con todo lo que venga.",
  "No pares, cada paso cuenta.",
  "Eres capaz de más de lo que imaginas.",
  "La constancia te hará invencible.",
  "Ve por ello. Tienes lo necesario.",
  "No te detengas ahora, el cambio está cerca.",
  "Tu futuro está construido por lo que hagas hoy.",
  "Estás en el camino correcto.",
  "Tu progreso es real, aunque no lo notes aún.",
  "Hazlo por la versión de ti que nunca se rindió.",
  "Nada que valga la pena es fácil, pero sí posible.",
  "Hoy es un buen día para empezar algo grande.",
  "El primer paso ya te diferencia del resto.",
  "La motivación viene y va, la disciplina se queda.",
  "No esperes el momento perfecto, créalo.",
  "Tú eres la razón por la que vas a lograrlo.",
  "Todo gran logro empezó con un pequeño intento.",
  "Confía en tu proceso.",
  "Persiste hasta que la meta se vuelva rutina.",
  "Hoy plantás esfuerzo, mañana cosecharás sueños.",
  "Tú tienes el poder de cambiar tu historia.",
  "Eres tu propia competencia, supérate cada día.",
  "Nada te detiene si tú no te detienes.",
  "Hazlo con miedo, pero hazlo.",
  "Tú defines tus límites.",
  "Cada paso hacia adelante ya es éxito.",
  "Naciste para brillar, no para conformarte."
  ],
  duelo: [
    "Es normal sentir dolor, pero no estás solo.",
  "El amor nunca muere, vive en tu corazón.",
  "Recuerda con cariño, honra su vida con la tuya.",
  "Permítete llorar, sanar y recordar con amor.",
  "Tu ser querido siempre estará contigo en tus recuerdos.",
  "El duelo no tiene tiempo, solo amor que sigue vivo.",
  "No es olvido, es aprender a vivir distinto.",
  "Llorar también es una forma de amar.",
  "Cada lágrima honra lo que significó esa persona.",
  "Sigue caminando, con su memoria como guía.",
  "El amor trasciende la ausencia física.",
  "Tus sentimientos son parte de la sanación.",
  "El tiempo no borra, transforma el dolor.",
  "El recuerdo es un puente hacia su presencia.",
  "No estás roto, estás en proceso de sanar.",
  "Honra su memoria con tus actos de amor.",
  "Permítete sentir cada emoción sin juicio.",
  "El dolor es la expresión del amor profundo.",
  "Cada día es un paso hacia la paz interior.",
  "No tienes que estar fuerte todo el tiempo.",
  "El duelo es amor que se expresa en tristeza.",
  "Hablar de tu pérdida es parte de sanar.",
  "No temas pedir ayuda, no estás solo.",
  "El amor permanece aunque no veas a quien amas.",
  "Date tiempo, el corazón sabe cómo sanar.",
  "Cada recuerdo guarda un pedazo de vida.",
  "No olvides que también mereces felicidad.",
  "El amor vivido es eterno, no termina con la muerte.",
  "Permite que la esperanza te acompañe.",
  "La memoria es el hogar del amor que no muere."
  ],
  estudios: [
   "Cada minuto que estudias, te acerca a tus sueños.",
  "No estudias para aprobar, estudias para superarte.",
  "Tu futuro yo te agradecerá el esfuerzo de hoy.",
  "El conocimiento es poder, y tú lo estás conquistando.",
  "El éxito es la suma de pequeños esfuerzos repetidos día tras día.",
  "Estudiar no es solo para aprobar, es para construir tu futuro.",
  "No sueñes con el éxito, trabaja para conseguirlo.",
  "Cada hora de estudio es una inversión en ti mismo.",
  "El conocimiento es el único tesoro que nadie puede quitarte.",
  "La disciplina hoy, es libertad mañana.",
  "Cada paso que das en tus estudios es un paso hacia tu meta.",
  "No te rindas ante las dificultades, son parte del aprendizaje.",
  "La paciencia y el esfuerzo construyen tu sabiduría.",
  "Aprender hoy es abrir puertas para el mañana.",
  "El estudio constante abre caminos nuevos.",
  "El esfuerzo es el puente entre metas y logros.",
  "Las dudas son oportunidades para crecer.",
  "La constancia es la clave del éxito académico.",
  "Estudia con pasión y verás resultados.",
  "Cada reto académico fortalece tu mente.",
  "No temas equivocarte, de los errores se aprende.",
  "El conocimiento transforma tu realidad.",
  "Cada libro es un paso hacia tu mejor versión.",
  "Tu esfuerzo de hoy es la recompensa de mañana.",
  "Sigue adelante, tu meta está cerca.",
  "El aprendizaje es un viaje, disfruta cada paso.",
  "La disciplina es el motor de tus éxitos.",
  "No postergues, cada día cuenta.",
  "Tu futuro depende de lo que hagas hoy.",
  "Estudiar es sembrar para cosechar futuro."
  ],
  trabajo: [
     "No todos los días serán perfectos, pero cada paso cuenta.",
  "Hoy puede que no tengas ganas, pero avanzar un poco ya es victoria.",
  "No lo hagas por motivación, hazlo por disciplina.",
  "A veces solo hay que empezar. El ánimo llega en el camino.",
  "Está bien no estar al 100%. Lo importante es seguir.",
  "Tu esfuerzo diario construye tu camino.",
  "Incluso un día difícil te acerca a tu meta.",
  "No subestimes lo que logras con constancia.",
  "Trabajas por tu presente y tu futuro.",
  "Hazlo por ti, por lo que mereces.",
  "Cada jornada es una oportunidad para crecer.",
  "El trabajo de hoy construye tus sueños de mañana.",
  "No permitas que la pereza controle tu vida.",
  "La constancia supera al talento cuando falta motivación.",
  "Levántate, aunque sea lento, pero levántate.",
  "Tu actitud puede cambiar cualquier día gris.",
  "El éxito es la suma de días en que decidiste seguir.",
  "Trabajar es invertir en tu libertad futura.",
  "No dejes que el cansancio te robe tu propósito.",
  "La disciplina es la base del éxito laboral.",
  "Cada esfuerzo cuenta, aunque no lo veas ya.",
  "El trabajo es el camino hacia tus metas personales.",
  "Incluso en la rutina hay aprendizaje y crecimiento.",
  "No necesitas ganas, solo decisión.",
  "Cada día trabajado es un paso hacia tus sueños.",
  "No subestimes tu poder para cambiar tu día.",
  "Hazlo por tu bienestar a largo plazo.",
  "Tu trabajo tiene valor, aunque hoy no lo sientas.",
  "Cada tarea realizada es un logro.",
  "Recuerda por qué comenzaste y sigue adelante."
  ],
  emociones: [
     "Tus emociones son válidas.",
  "La tormenta pasará, siempre lo hace.",
  "Cada emoción es una señal.",
  "No hay emociones buenas o malas, solo humanas.",
  "Sentir es vivir plenamente.",
  "Escucha lo que tus emociones quieren decirte.",
  "Abrázate cuando lo necesites.",
  "No estás roto por sentir mucho.",
  "Tu sensibilidad es tu fuerza.",
  "Permítete sentir sin culpa.",
  "Reconocer tus emociones es el primer paso para sanarlas.",
  "No reprimas lo que sientes, déjalo fluir.",
  "Las emociones nos enseñan sobre nosotros mismos.",
  "Cada sentimiento tiene un propósito.",
  "La aceptación es clave para la paz interior.",
  "Tus emociones te conectan con tu verdad.",
  "No luches contra tus sentimientos, acompáñalos.",
  "Sentir profundamente es vivir con autenticidad.",
  "Las emociones son el lenguaje del alma.",
  "Ser emocional no es debilidad, es humanidad.",
  "Deja que tus emociones te guíen, no te controlen.",
  "Cada emoción es un maestro disfrazado.",
  "Tus sentimientos merecen respeto y espacio.",
  "Hablar de tus emociones libera cargas.",
  "No estás solo en lo que sientes.",
  "Cada día es una oportunidad para equilibrar tus emociones.",
  "El autocuidado también incluye cuidar tu salud emocional.",
  "Expresar tus emociones es un acto de valentía.",
  "No temas mostrar lo que sientes.",
  "La salud emocional es tan importante como la física."
  ],
  relaciones: [
     "Rodéate de quienes suman luz.",
  "Las conexiones sinceras curan.",
  "Cuida de quien te cuida.",
  "El amor también se aprende y se cultiva.",
  "Mereces relaciones sanas y recíprocas.",
  "Escuchar es una forma de amar.",
  "No estás solo, hay quienes te valoran.",
  "Tú también mereces atención y respeto.",
  "Una buena amistad vale más que mil palabras.",
  "Las relaciones se construyen con tiempo y empatía.",
  "El respeto es la base de toda relación.",
  "La confianza se gana con acciones, no palabras.",
  "Aprende a comunicar tus necesidades con amor.",
  "El perdón libera y sana relaciones.",
  "No temas poner límites saludables.",
  "Las relaciones verdaderas te hacen crecer.",
  "Valora a quienes están contigo en las buenas y en las malas.",
  "No te conformes con menos de lo que mereces.",
  "El cariño sincero es un regalo invaluable.",
  "Las amistades auténticas son un tesoro.",
  "Comparte momentos, no solo palabras.",
  "La empatía fortalece cualquier vínculo.",
  "Aprende a amar sin perderte a ti mismo.",
  "Cultiva la paciencia en tus relaciones.",
  "Cada persona en tu vida aporta una lección.",
  "No temas alejarte de relaciones tóxicas.",
  "El amor propio mejora todas las relaciones.",
  "Las pequeñas acciones dicen más que grandes gestos.",
  "Ser auténtico atrae relaciones genuinas.",
  "Agradece a quienes te hacen sentir bien."
  ],
  crecimiento_personal: [
    "Cada reto te hace más fuerte.",
  "Tu mejor versión está en camino.",
  "No estás estancado, estás tomando impulso.",
  "El cambio comienza contigo.",
  "Nunca es tarde para reinventarte.",
  "Cree en ti, incluso cuando nadie más lo haga.",
  "Sal de tu zona de confort, ahí pasa la magia.",
  "Tu progreso es más importante que la perfección.",
  "Confía en el proceso, estás avanzando.",
  "La evolución personal no es lineal, es única.",
  "Cada día es una nueva oportunidad para mejorar.",
  "Aprender de tus errores es crecer de verdad.",
  "No te compares, solo compite contigo mismo.",
  "El crecimiento duele, pero vale la pena.",
  "Desafíate a ti mismo cada día.",
  "La disciplina es tu mejor aliada.",
  "Rodéate de personas que te inspiren.",
  "Las pequeñas mejoras constantes son poderosas.",
  "Tu mente es tu mayor recurso, cuídala.",
  "La paciencia es clave en tu transformación.",
  "Reconoce y celebra tus logros.",
  "La humildad abre la puerta al aprendizaje.",
  "Cada cambio comienza con una decisión.",
  "No temas pedir ayuda en tu camino.",
  "Las dificultades son oportunidades disfrazadas.",
  "Construye hábitos que te impulsen.",
  "El autoconocimiento es el primer paso.",
  "Sé amable contigo mismo en el proceso.",
  "Visualiza el futuro que deseas y trabaja por él.",
  "Cree en tu capacidad de evolucionar."
  ],
  deporte: [
    "El cuerpo logra lo que la mente cree.",
  "Hazlo por ti, por tu salud, por tu fuerza.",
  "Aunque no tengas ganas, 5 minutos pueden cambiar tu día.",
  "El esfuerzo de hoy es el orgullo de mañana.",
  "Moverte es amarte. ¡Hazlo aunque sea poco!",
  "El sudor de hoy es la sonrisa de mañana.",
  "Nadie empieza siendo experto. Solo empieza.",
  "Entrenar es una forma de cuidarte.",
  "La constancia es más fuerte que la motivación.",
  "Cada movimiento te lleva a un tú más fuerte.",
  "Tu cuerpo es tu templo, cuídalo con respeto.",
  "Cada gota de sudor es un paso hacia tu meta.",
  "El dolor es temporal, el orgullo es para siempre.",
  "La disciplina en el deporte transforma vidas.",
  "No te compares con otros, solo contigo mismo.",
  "El descanso es parte fundamental del entrenamiento.",
  "Entrena hoy para agradecer mañana.",
  "El deporte fortalece cuerpo y mente.",
  "Los pequeños avances suman grandes logros.",
  "Cada día activo es un regalo para tu salud.",
  "Sé constante, los resultados llegan.",
  "Tu esfuerzo hoy será tu fuerza mañana.",
  "Muévete por amor a ti mismo.",
  "No dejes que el cansancio venza tu voluntad.",
  "Tu cuerpo puede mucho más de lo que imaginas.",
  "Cada paso cuenta en tu camino deportivo.",
  "Entrena con propósito y pasión.",
  "El compromiso contigo es el mejor entrenamiento.",
  "Disfruta el proceso, no solo el resultado.",
  "Haz del deporte un hábito, no una obligación."
  ],
  hueso_ancho: [
   "Tu cuerpo es una fortaleza, no una disculpa.",
  "El valor no tiene talla.",
  "Eres digno/a exactamente como eres.",
  "La belleza real no cabe en una etiqueta.",
  "No necesitas encajar en moldes ajenos.",
  "Tu fuerza interna es lo que realmente importa.",
  "Estás diseñado/a para destacar, no para encajar.",
  "Eres una obra de arte única e irrepetible.",
  "Camina con seguridad, tu presencia impacta.",
  "Tu cuerpo es tu hogar, ámalo sin condiciones.",
  "La confianza viene de aceptarte tal cual eres.",
  "No permitas que nadie defina tu valor.",
  "La verdadera belleza está en tu autenticidad.",
  "Eres fuerte porque eres tú, sin comparaciones.",
  "El amor propio rompe cualquier molde.",
  "Tu cuerpo merece respeto y cuidado.",
  "Sé orgulloso/a de quién eres y cómo eres.",
  "El tamaño no define tu valor ni tu fuerza.",
  "Eres suficiente y mereces lo mejor.",
  "Tu presencia llena espacios con autenticidad.",
  "Celebra tus diferencias, son tu poder.",
  "La aceptación comienza contigo mismo/a.",
  "Eres inspiración para quienes te rodean.",
  "Tu esencia es más fuerte que cualquier estándar.",
  "El amor propio es tu mejor armadura.",
  "No te compares, brilla con tu luz propia.",
  "Cada paso seguro reafirma tu valor.",
  "Tu cuerpo cuenta una historia de fortaleza.",
  "Sé la mejor versión de ti, sin excusas.",
  "La confianza transforma cualquier inseguridad."
  ],
  deprimido: [
    "Aunque hoy parezca gris, el sol siempre vuelve.",
  "Tu existencia ya tiene valor por sí sola.",
  "Respira. Sobrevivir también es una victoria.",
  "Estás haciendo lo mejor que puedes, y eso basta.",
  "El dolor no te define, te transforma.",
  "Incluso el árbol más fuerte empezó como semilla.",
  "No estás solo/a, y eso ya es esperanza.",
  "Tus emociones son válidas, no te castigues por sentir.",
  "Cada día que te levantas es un acto de valentía.",
  "Permítete sanar a tu ritmo, sin prisa ni culpa.",
  "La oscuridad es temporal, la luz volverá.",
  "Eres más fuerte de lo que imaginas.",
  "No temas pedir ayuda cuando la necesites.",
  "El descanso es parte del proceso de recuperación.",
  "Tus pensamientos no son la realidad completa.",
  "Cada pequeño avance es un gran logro.",
  "No te juzgues por sentirte así.",
  "Hay esperanza incluso en los días más oscuros.",
  "Permítete sentir sin miedo ni culpa.",
  "El amor propio es la base de la sanación.",
  "Hablar ayuda a aliviar la carga interior.",
  "La depresión no define quién eres.",
  "Confía en que puedes superar esta etapa.",
  "Tu valor no depende de tu estado emocional.",
  "Busca la belleza en los pequeños detalles.",
  "Cada paso hacia adelante es un triunfo.",
  "No estás solo, hay apoyo y comprensión.",
  "Permítete momentos de alegría cuando puedas.",
  "Eres importante, incluso cuando no lo sientes.",
  "La vida puede sorprenderte con nuevas esperanzas."
  ]
};

let ultimaCategoria = "";
let ultimaFrase = "";

function mostrarFraseCategoria() {
  const select = document.getElementById("categoria");
  const categoria = select.value;
  const fraseContenedor = document.getElementById("frase");

  if (!categoria || !frases[categoria] || frases[categoria].length === 0) {
    fraseContenedor.textContent = "Por favor, selecciona una categoría válida.";
    return;
  }

  const lista = frases[categoria];
  const nuevaFrase = lista[Math.floor(Math.random() * lista.length)];

  fraseContenedor.textContent = nuevaFrase;
  ultimaCategoria = categoria;
  ultimaFrase = nuevaFrase;

  document.body.className = "";
  document.body.classList.add(categoria);

  document.getElementById("btn-otra-cat").style.display = "inline-block";
}

function otraFraseCategoria() {
  if (!ultimaCategoria || !frases[ultimaCategoria]) return;

  let nuevaFrase;
  do {
    nuevaFrase = frases[ultimaCategoria][Math.floor(Math.random() * frases[ultimaCategoria].length)];
  } while (nuevaFrase === ultimaFrase && frases[ultimaCategoria].length > 1);

  document.getElementById("frase").textContent = nuevaFrase;
  ultimaFrase = nuevaFrase;
}

document.addEventListener("DOMContentLoaded", () => {
  const btnFrase = document.getElementById("btn-frase");
  const btnOtra = document.getElementById("btn-otra-cat");

  if (btnFrase && btnOtra) {
    btnFrase.addEventListener("click", mostrarFraseCategoria);
    btnOtra.addEventListener("click", otraFraseCategoria);
  } else {
    console.error("No se encontraron los botones necesarios.");
  }
});
